version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: ssh-a
    privileged: true
    restart: always
    networks:
      - web_network
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  web_network:
    driver: bridge 